name: Self-Hosted Build and Release

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: self-hosted # This specifies that it should run on the self-hosted agent

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Run Hello World
      run: python hello.py
      
  release:
    needs: build
    runs-on: self-hosted # This specifies that it should run on the self-hosted agent
    
    steps:
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      with:
        files: |
          hello.py
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Get Release URL
      run: echo "steps.create_release.outputs.upload_url"
