name: Release Demo

on:
  push:
    branches:
      - master

jobs:
  release:
    name: Release
    runs-on: self-hosted

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.x  # Use the Python version you need

    - name: Install dependencies
      run: pip install -r requirements.txt  # If you have any dependencies

    - name: Build Release Artifact
      run: |
        python hello.py  # Run your Python script
        mkdir release
        mv hello.py release/
        tar -czvf release.tar.gz release/
      shell: bash

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      with:
        files: |
          release.tar.gz
        token: ${{ secrets.GITHUB_TOKEN }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
