name: Self-Hosted Build and Release


on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: self-hosted

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Install Python 3.11.3
      run: |
        # Download Python installer
        Invoke-WebRequest -Uri https://www.python.org/ftp/python/3.11.3/python-3.11.3-amd64.exe -OutFile python-installer.exe

        # Install Python
        Start-Process -Wait -FilePath python-installer.exe -ArgumentList "/quiet InstallAllUsers=1 PrependPath=1 Include_launcher=0"
      shell: powershell
      
    - name: Install Python Dependencies
      run: |
        # Install Python dependencies from requirements.txt (if it exists)
        if (Test-Path "requirements.txt") {
          pip install -r requirements.txt
        } else {
          echo "requirements.txt not found."
        }
      shell: powershell
      
    - name: Run Hello World
      run: python hello.py
      working-directory: ${{ github.workspace }}

  release:
    needs: build
    runs-on: self-hosted

    steps:
    - name: Create GitHub Release
      id: create_release
      uses: softprops/action-gh-release@v1
      with:
        files: hello.py
        tag_name: v1.0  # Replace with your desired tag name
        draft: false
        prerelease: false
        commitish: master  # Replace with your desired branch
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Get Release URL
      run: echo "steps.create_release.outputs.tag_name"
