on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11.3'

      - name: Install Python Dependencies
        run: |
          if (Test-Path "requirements.txt") {
            python -m pip install -r requirements.txt
          } else {
            Write-Host "requirements.txt not found."
          }

      - name: Run Hello World
        run: python hello.py
        working-directory: ${{ github.workspace }}
        shell: powershell

  release:
    needs: build
    runs-on: self-hosted
    steps:
      - name: Calculate Semantic Version
        id: calculate_version
        run: |
          $calculated_version = Get-Date -Format 'yyyyMMdd'
          Write-Host "Calculated version: $calculated_version"
          Write-Host "##vso[task.setvariable variable=version;isOutput=true]$calculated_version"

      - name: Create GitHub Release
        id: create_release
        run: |
          $tag_name = $env:version
          Write-Host "Creating GitHub Release with tag $tag_name"

      - name: Get Release URL
        run: |
          $release_url = "https://github.com/${{ github.repository }}/releases/tag/v$env:version"
          Write-Host "Release URL: $release_url"
