name: Build and Release

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch name'
        required: true
        default: 'master'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11'

      - name: Install Python Dependencies
        run: |
          # Install Python dependencies from requirements.txt (if it exists)
          if [ -f "requirements.txt" ]; then
            python -m pip install -r requirements.txt
          else
            echo "requirements.txt not found."
          fi

      - name: Run Hello World
        run: python hello.py
        working-directory: ${{ github.workspace }}

  release:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@v1
        with:
          tag_name: "v1.${{ github.run_number }}"
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}

      - name: Get Release URL
        run: echo "Release URL:https://github.com/${{ github.repository }}/releases/tag/v1.${{ github.run_number }}"
