on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11'

      - name: Install Python Dependencies
        run: |
          if [ -f "requirements.txt" ]; then
            python -m pip install -r requirements.txt
          else
            echo "requirements.txt not found."
          fi

      - name: Run Hello World
        run: python hello.py
        working-directory: ${{ github.workspace }}

  release:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Calculate Semantic Version
        id: calculate_version
        run: |
          # Replace this with your logic to calculate the semantic version
          # Example: Calculate the version based on the date
          calculated_version=$(date +'%Y.%m.%d')
          echo "::set-output name=version::$calculated_version"
        shell: bash

      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@v1
        with:
          tag_name: "${{ steps.calculate_version.outputs.version }}"
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}

      - name: Get Release URL
        run: |
          release_url="https://github.com/${{ github.repository }}/releases/tag/v1.${{ steps.calculate_version.outputs.version }}"
          echo "Release URL: $release_url"
